language: ruby

sudo: false



before_install: 
  - gem install httparty
  - gem install bundler

env:
  - RAILS_VERSION="~> 3.2.22"
  - RAILS_VERSION="~> 4.0.13"
  - RAILS_VERSION="~> 4.1.13"
  - RAILS_VERSION="~> 4.2.4"

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.4
  - 2.2.2
