language: ruby


before_install: gem install bundler -v 1.10.6


env:
  - RAILS_VERSION="~> 3.2.22"
  - RAILS_VERSION="~> 4.0.13"
  - RAILS_VERSION="~> 4.1.13"
  - RAILS_VERSION="~> 4.2.4"

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.4
  - 2.2.2
